config/routes.rb
Rails.application.routes.draw do
  resources :material_types
  resources :collection_points
  get 'contact/new'
  root 'collection_points#home'
  get 'home', to: "collection_points#home"
  get 'about', to: "collection_points#about"
  get 'contact', to: "collection_points#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection_point.rb
class CollectionPoint < ApplicationRecord

    validates :name, :state, :city, :address, presence: true
    
    validates :name, format: { with: /\A[\p{L}\p{M}\-\s]+\z/, 
                                     message: "Nome: Apenas letras, espaços e traços." },
                     length: { minimum: 2, message: "Nome: Mínimo de dois caracteres." }

    validates :city, format: { with: /\A[\p{L}\p{M}\-\s]+\z/, 
                                     message: "Cidade: Apenas letras, espaços e traços." },
                     length: { minimum: 3, message: "Cidade: Mínimo de três caracteres." }

    validates :address, format: { with: /\A[\p{L}\p{M}\-\s\,0-9]+\z/, 
                                        message: "Endereço: Apenas letras, espaços e vírgulas." }
                                        
    validates :phone, :allow_blank => true, 
                      length: { within: 3..15, message: "Telefone válido: Entre 3 e 15 caracteres." }, 
                      format: { with: /\A[\d\-()]+\z/, 
                                message: "Telefone: Apenas números." }
    
    before_save :normalize_fields
    belongs_to :material_type, optional: true

    def normalize_fields
       self.name = Normalizer.new.normalize(self.name)

       self.state = Normalizer.new.normalize(self.state)

       self.city = Normalizer.new.normalize(self.city)

       self.address = Normalizer.new.normalize(self.address)

       self.phone = Normalizer.new.normalize_phone(self.phone)
    end
end

app/models/material_type.rb
class MaterialType < ApplicationRecord
    has_many :collection_points
end

app/models/normalizer.rb
class Normalizer
    def normalize(string)
        string.to_s.parameterize(separator: " ").upcase
    end

    def normalize_phone(phone)
        phone.tr('^0-9', '')  
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collection_points_controller.rb
class CollectionPointsController < ApplicationController
  before_action :set_collection_point, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      normalized_search = Normalizer.new.normalize(params[:search])
      @collection_points = CollectionPoint.where("name like ? OR city like ? OR state like ?", "%#{normalized_search}%", "%#{normalized_search}%", "%#{normalized_search}%")
      if @collection_points.empty?
        flash[:danger] = "Não há registros desse local/cidade ☹ Se descobrir um, nos ajude inserindo aqui! 😁"
      else
        @collection_points
      end

    else 
      @collection_points = CollectionPoint.all
      @collection_points = CollectionPoint.order(name: :desc)
    end
  end

  def show
  end

  def new
    @collection_point = CollectionPoint.new
  end

  def edit
  end

  def home
  end

  def about
  end

  def contact
  end

  def create
    @collection_point = CollectionPoint.new(collection_point_params)

    respond_to do |format|
      if @collection_point.save
        flash[:notice] = "Local criado com sucesso!"
        format.html { redirect_to collection_points_path }
        format.json { render :show, status: :created, location: @collection_point }
      else
        flash[:notice] = "Insira local de coleta no formato adequado"
        format.html { render :new }
        format.json { render json: @collection_point.errors }
      end
    end
  end

  def update
    respond_to do |format|
      if @collection_point.update(collection_point_params)
        format.html { redirect_to @collection_point }
      else
        format.html { render :edit }
        format.json { render json: @collection_point.errors }
      end
    end
  end

  def destroy
    @collection_point.destroy
    respond_to do |format|
      format.html { redirect_to @collection_point, notice: 'Local de coleta apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_collection_point
      @collection_point = CollectionPoint.find(params[:id])
    end
    def collection_point_params
      params.permit(:name, :state, :city, :address, :phone, :obs, :material_type_id )
    end
end

app/controllers/material_types_controller.rb
class MaterialTypesController < ApplicationController
  before_action :set_material_type, only: [:show, :edit, :update, :destroy]

  # GET /material_types
  # GET /material_types.json
  def index
    @material_types = MaterialType.all
  end

  # GET /material_types/1
  # GET /material_types/1.json
  def show
  end

  # GET /material_types/new
  def new
    @material_type = MaterialType.new
  end

  # GET /material_types/1/edit
  def edit
  end

  # POST /material_types
  # POST /material_types.json
  def create
    @material_type = MaterialType.new(material_type_params)

    respond_to do |format|
      if @material_type.save
        format.html { redirect_to @material_type, notice: 'Material type was successfully created.' }
        format.json { render :show, status: :created, location: @material_type }
      else
        format.html { render :new }
        format.json { render json: @material_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /material_types/1
  # PATCH/PUT /material_types/1.json
  def update
    respond_to do |format|
      if @material_type.update(material_type_params)
        format.html { redirect_to @material_type, notice: 'Material type was successfully updated.' }
        format.json { render :show, status: :ok, location: @material_type }
      else
        format.html { render :edit }
        format.json { render json: @material_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /material_types/1
  # DELETE /material_types/1.json
  def destroy
    @material_type.destroy
    respond_to do |format|
      format.html { redirect_to material_types_url, notice: 'Material type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material_type
      @material_type = MaterialType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def material_type_params
      params.require(:material_type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collection_points_helper.rb
module CollectionPointsHelper
end

app/helpers/material_types_helper.rb
module MaterialTypesHelper
end

app/views/collection_points/_form.html.erb
<%= form_with(model: collection_points, local: true, class:"form-group") do |form| %>
  <div class="row">
    <div class="form-group col-md-6">
      <%= form.label :nome, '* Nome', class:"col-md control-label" %>
      <%= form.text_field :name, placeholder: "Ex: Supermercado Big", class:"form-control", required: true %>
    </div>
    
    <div class="form-group col-md-6">
      <%= form.label :estado, '* Estado', class:"col control-label" %>
      <%= form.select :state, ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'], class:"form-control", id: "js-searchable", required: true %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :cidade, '* Cidade', class:"col control-label" %>
      <%= form.text_field :city, placeholder: "Ex: Florianópolis", class:"form-control", required: true %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :endereço, '* Endereço', class:"col control-label" %>
      <%= form.text_field :address, placeholder: "Ex: Rua dos limões, 1200/44", class:"form-control", required: true %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :telefone, class:"col control-label" %>
      <%= form.text_field :phone, placeholder: "(xx)12345-6789", class:"form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :observação, class:"col control-label" %>
      <%= form.text_field :obs, placeholder: "Ex: Ponto de coleta em frente ao estacionamento", class:"form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :type_of_material, '* Tipo de material', class:"col control-label" %>
      <%= form.collection_select :material_type_id, MaterialType.all, :id, :name, {}, class:"form-control" %>
    </div>
    
    <div class="actions ml-4">
      <%= form.submit "Criar", class:"btn btn-secondary" %>
      <%= link_to 'Voltar', root_path, class:"btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/collection_points/about.html.erb
<%= image_tag ("01.png"), class: "big-image-about p-0 m-0" %>
<div class="container pt-5 pb-5">
    <p class="text-about">O lixo especial é todo material que, por conta de suas características físicas e químicas, não pode ser descartado junto com o lixo comum ou reciclável (como pilhas, baterias, vidro quebrado e óleo de cozinha). Esses resíduos precisam receber tratamento diferenciado para que seu descarte não prejudique drasticamente o meio ambiente.</p>
</div>
<%= image_tag ("lam2.jpg"), class: "big-image-about p-0 m-0" %>
<div class="container pt-5 pb-5">
    <p class="text-about">Infelizmente, o Brasil não tem um programa que lide com materiais especiais, deixando a responsabilidade na mão da indústria produtora dos materiais. Por conta disso, normalmente se depende do consumidor fazer a devolução e descobrir se a empresa em questão recebe esse produto após seu uso, o que nem sempre acontece.</p>
</div>
<%= image_tag ("vidro2.jpg"), class: "big-image-about p-0 m-0" %>
<div class="container pt-5 pb-5">
    <p class="text-about">Não é comum ouvirmos falar de programas de devolução de materiais especiais, e mesmo ouvimos, nem sempre temos pontos de coleta facilitados para a entrega.</p>
    <p class="text-about">É importante se informar sobre o descarte correto de materiais que não são considerados recicláveis ou lixo orgânico, e nós estamos aqui pra te ajudar :)</p>
</div>

app/views/collection_points/contact.html.erb
<div class="container">
    <p class="text-contact">Dúvidas, sugestões, divagações e trocas de figurinhas:</p>
    <p class="mail-contact">ondetemcoleta@gmail.com</p>
</div>

app/views/collection_points/edit.html.erb
<div class="container">
    <h2>Editar: <%= @collection_point.name %></h2>
    <h4 class="subtitles pb-4 pt-3"> * requerido </h4>
</div>

<% if flash[:notice] %>
    <div class="alert alert-danger" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>


<%= render 'form', collection_points: @collection_point %>

app/views/collection_points/home.html.erb
<div class="container-md container-fluid m-auto">
  <div class="text-center">
    <div class="row justify-content-md-center">
      <div class="col col-sm-12 col-12 pt-4">
        <p class="home-text">Onde tem coleta é uma iniciativa que visa facilitar o descarte correto de materiais que requerem tratamento especial: pilhas, baterias, óleo de cozinha, esponjas, medicamentos e outros.</p>
      </div>
    </div>
      <div class="col pt-4">
        <%= link_to "INSERIR NOVO PONTO DE COLETA", new_collection_point_path , html_options = {class:"btn btn-success button-font text-white insert-search-button"} %>
        <div class="row">
          <div class="col">
            <div class="card card-body-search mt-0">
              <%= form_tag collection_points_path, method: :get, class:"" do %>
                  <%= label_tag(:q, "Search for:") %>
                <div class="form-group col pt-1 m-auto">
                  <%= text_field_tag "search", @name, placeholder: "Digite o nome do local ou cidade", class:"form-control" %> 
                </div>
                <div class="form-group col pt-3">
                  <%= button_to "BUSCAR", collection_points_path, class:"btn btn-success insert-search-button button-font text-white" %> 
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/collection_points/index.html.erb
<div class="container-md container-fluid m-auto">
  <% if flash[:notice] %>
    <div class="notice alert alert-success" role="alert""><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:danger] %>
    <div class="notice alert alert-danger" role="alert""><%= flash[:danger] %></div>
  <% end %>

  <table class="table table-bordered table-hover table-striped table-responsive table-show" >
    <thead class="table-secondary table-head">
      <tr>
        <th class="table-content" scope="col">LOCAL</th>
        <th class="table-content" scope="col">ESTADO</th>
        <th class="table-content" scope="col">CIDADE</th>
        <th class="table-content" scope="col">ENDEREÇO</th>
        <th class="table-content" scope="col">TELEFONE</th>
        <th class="table-content" scope="col">OBSERVAÇÃO</th>
        <th class="table-content" scope="col">TIPO DE MATERIAL</th>
      </tr>
    </thead>
    <tbody>
      <% @collection_points.each do |collection_point| %>
        <tr>
        <td class="table-content"><%= link_to "#{collection_point.name}", collection_point%></td>
        <td class="table-content"><%= collection_point.state %></td>
        <td class="table-content"><%= collection_point.city %></td>
        <td class="table-content"><%= collection_point.address %></td>
        <td class="table-content"><%= collection_point.phone %></td>
        <td class="table-content"><%= collection_point.obs %></td>
        <td class="table-content"><%= collection_point.material_type.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'Novo local', new_collection_point_path, class:"btn btn-secondary" %>
  <%= link_to 'Voltar', root_path, class:"btn btn-secondary" %>
</div>

app/views/collection_points/new.html.erb
<div class="container-md container-fluid m-auto">
  <div class="container title"><h2>Inserir novo local</h2>
  <h4 class="subtitles pb-4 pt-3"> * requerido </h4>
  </div>
  <% if @collection_point.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul class="pt-3">
        <% @collection_point.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form', collection_points: @collection_point, redirect_to: root_path %>
</div>

app/views/collection_points/show.html.erb
<div class="card border-success text-center mb-4 mt-4">
  <div class="card-header"><%= @collection_point.name %></div>
  <div class="card-body">
  <p>
  <%= @collection_point.city %>, <%= @collection_point.state %>
  </p>
  <p>
    <%= @collection_point.address %>
  </p>
  <p>
    <%= @collection_point.phone %>
  </p>
  <p>
    <%= @collection_point.obs %>
  </p>
  </div>
</div>

<%= link_to 'Voltar', collection_points_path, class:"btn btn-secondary" %>

app/views/collection_points/teste.html.erb
<div class="text-center pb-5">
    <div class="pt-3 pb-5">
      <div class="row justify-content-md-center">
        <div class="form-group col-8">
          <p class="card-text p-2 home-text">Onde tem coleta é uma iniciativa que visa facilitar o descarte correto de materiais que requerem tratamento especial: pilhas, baterias, óleo de cozinha, esponjas, medicamentos e outros.</p>
        </div>
      </div>
      <%= link_to "INSERIR NOVO PONTO DE COLETA", new_collection_point_path , html_options = {class:"btn btn-success button-font text-white insert-search-button"} %>
    </div>
    <%= form_tag collection_points_path, method: :get, class:"" do %>
      <div class="row justify-content-md-center">
        <div class="form-group col-6">
          <%= text_field_tag "search", @name, placeholder: "Digite o nome da cidade, local ou sigla do estado", class:"form-control" %> 
        </div>
      </div>
      <div class="row justify-content-md-center">
        <div class="col-6">
          <%= button_to "BUSCAR PONTO DE COLETA", nil, class:"btn btn-success insert-search-button button-font text-white" %> 
        </div>
      </div>
    <% end %>
</div>

app/views/collection_points/update.html.erb
<div class="container">
    <h2>Editar: <%= @collection_point.name %></h2>
    <h4 class="subtitles pb-4 pt-3"> * requerido </h4>
</div>

<% if flash[:notice] %>
    <div class="alert alert-danger" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>


<%= render 'form', collection_points: @collection_point %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "Onde tem coleta?" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Onde tem coleta?" %>">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&family=Lato&family=Montserrat&family=Oswald&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="card card-border logo-image text-center mt-4">
        <div class="card-body p-0 mb-0">
          <a href="/"> <%= image_tag ("3.png") %> </a> 
        </div>
        <hr class="hr pt-0 mt-0">
        <div class="card-body pt-3">
          <a href="about" class="card-link">sobre o projeto</a>
          <a href="contact" class="card-link">fale conosco</a>
        </div>
      </div>
    </header>
      <main>
        <%= yield %>
      </main>
    <footer class="pt-4 pb-4">
      <div class="container home-text">
        <div class="text-center text-footer p-3 nav-footer-bg">
          © 2020 Copyright
          <a class="text-dark text-footer" href="">ondetemcoleta</a>
        </div>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/material_types/_form.html.erb
<%= form_with(model: material_type, local: true) do |form| %>
  <% if material_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material_type.errors.count, "error") %> prohibited this material_type from being saved:</h2>

      <ul>
        <% material_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/material_types/edit.html.erb
<h1>Editing Material Type</h1>

<%= render 'form', material_type: @material_type %>

<%= link_to 'Show', @material_type %> |
<%= link_to 'Back', material_types_path %>

app/views/material_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Material Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @material_types.each do |material_type| %>
      <tr>
        <td><%= material_type.name %></td>
        <td><%= link_to 'Show', material_type %></td>
        <td><%= link_to 'Edit', edit_material_type_path(material_type) %></td>
        <td><%= link_to 'Destroy', material_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material Type', new_material_type_path %>

app/views/material_types/new.html.erb
<h1>New Material Type</h1>

<%= render 'form', material_type: @material_type %>

<%= link_to 'Back', material_types_path %>

app/views/material_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @material_type.name %>
</p>

<%= link_to 'Edit', edit_material_type_path(@material_type) %> |
<%= link_to 'Back', material_types_path %>